french_schools = [
  "École centrale de Marseille",
  "École polytechnique universitaire de Marseille de l'université d'Aix-Marseille",
  "Université de technologie de Compiègne",
  "École supérieure de chimie organique et minérale",
  "École supérieure d'ingénieurs en électronique et électrotechnique d'Amiens",
  "École nationale supérieure de mécanique et des microtechniques",
  "Université de technologie de Belfort-Montbéliard",
  "Institut supérieur d'ingénieurs de Franche-Comté de l'université de Besançon",
  "Institut polytechnique de Bordeaux - École nationale supérieure de chimie, de biologie et de physique",
  "Institut polytechnique de Bordeaux - École nationale supérieure d'électronique, informatique, télécommunications, mathématique et mécanique de Bordeaux",
  "Institut polytechnique de Bordeaux - École nationale supérieure de technologie des biomolécules de Bordeaux",
  "Institut polytechnique de Bordeaux - École nationale supérieure en environnement, géoressources et ingénierie du développe-ment durable",
  "École nationale supérieure en génie des techno-logies industrielles de l'université de Pau",
  "École nationale supérieure des sciences agronomiques de Bordeaux Aquitaine",
  "École supérieure des technologies industrielles avancées",
  "École nationale supérieure d'ingénieurs de Caen",
  "École d'ingénieurs de l’université de Caen",
  "École supérieure d'ingénieurs des travaux de la construction de Caen",
  "École nationale supérieure de chimie de Clermont-Ferrand",
  "Institut français de mécanique avancée",
  "Centre universitaire des sciences et techniques de l'université Clermont-Ferrand II",
  "Institut supérieur d'informatique, de modélisation et de leurs applications de l'université Clermont-Ferrand II",
  "École supérieure d'ingénieurs de recherche en matériaux de l'université de Dijon",
  "Institut supérieur de l'automobile et des transports de Nevers de l'université de Dijon",
  "Institut national supérieur des sciences agronomiques, de l'alimentation et de l'environnement",
  "Institut polytechnique de Grenoble, spécialité management technologique",
  "École nationale supérieure de l'énergie, l'eau et l'environnement de l'institut polytechnique de Grenoble - École nationale supérieure de l'énergie, l'eau et l'environnement",
  "École nationale supérieure de génie industriel de l'Institut polytechnique de Grenoble",
  "École nationale supérieure d'informatique et de mathématiques appliquées de l'Institut polytechnique de Grenoble",
  "École nationale supérieure de physique, électronique, matériaux de l'Institut polytechnique de Grenoble",
  "École nationale supérieure en systèmes avancés et réseaux de l'Institut polytechnique de Grenoble",
  "École internationale du papier, de la communication imprimée et des biomatériaux de l'Institut polytechnique de Grenoble",
  "École polytechnique universitaire de Savoie de l'université de Chambéry",
  "École polytechnique de l'Université Grenoble Alpes",
  "École centrale de Lille",
  "École nationale supérieure des arts et industries textiles",
  "École nationale supérieure de chimie de Lille",
  "École nationale supérieure d'ingénieurs en informatique, automatique, mécanique, énergétique et électronique de l'université de Valenciennes",
  "École polytechnique universitaire de Lille de l'université Lille-I",
  "École nationale supérieure des mines de Douai",
  "École d'ingénieurs du Littoral-Côte-d'Opale de l’université du littoral",
  "École des hautes études d'ingénieur du groupe HEI-ISA-ISEN",
  "Institut supérieur de l'électronique et du numérique de Lille du groupe HEI-ISA-ISEN",
  "Institut supérieur d'agriculture de Lille du groupe HEI-ISA-ISEN",
  "École nationale supérieure de céramique industrielle",
  "École nationale supérieure d'ingénieurs de Limoges de l'université de Limoges",
  "Institut d'ingénierie informatique de Limoges",
  "École centrale de Lyon",
  "École nationale d'ingénieurs de Saint-Étienne",
  "Institut national des sciences appliquées de Lyon",
  "École polytechnique universitaire de l'université Lyon-I",
  "École nationale des travaux publics de l’État",
  "École nationale supérieure des mines de Saint-Étienne",
  "Institut d’enseignement supérieur et de recherche en alimentation, santé animale, sciences agronomiques et de l’environne-ment",
  "École supérieure de chimie, physique, électronique de Lyon",
  "Institut textile et chimique de Lyon",
  "Institut supérieur d'agriculture Rhône-Alpes",
  "École nationale supérieure de chimie de Montpellier",
  "École polytechnique universitaire de Montpellier de l'université de Montpellier",
  "Institut national d'études supérieures agronomiques de Montpellier",
  "École nationale supérieure des mines d'Alès",
  "École nationale d'ingénieurs de Metz de l'université de Lorraine",
  "École européenne d'ingénieurs en génie des matériaux de l'université de Lorraine",
  "École nationale supérieure des mines de Nancy de l'université de Lorraine",
  "École nationale supérieure d'agronomie et des industries alimentaires de l'université de Lorraine",
  "École nationale supérieure d'électricité et de mécanique de Nancy de l'université de Lorraine",
  "École nationale supérieure de géologie de l'université de Lorraine",
  "École nationale supérieure en génie des systèmes et de l’innovation de l'université de Lorraine",
  "École nationale supérieure des industries chimiques de l'université de Lorraine",
  "École nationale supérieure des technologies et industries du bois de l'université de Lorraine",
  "École supérieure des sciences et technologies de l'ingénieur de Nancy de l'université de Lorraine",
  "École supérieure d'ingénieurs des travaux de la construction de Metz",
  "École centrale de Nantes",
  "École polytechnique de l'Université de Nantes",
  "École nationale supérieure d'ingénieurs du Mans de l'université du Mans",
  "Institut des sciences et techniques de l'ingénieur d'Angers de l'université d'Angers",
  "École nationale vétérinaire, agroalimentaire et de l'alimentation de Nantes-Atlantique",
  "École nationale supérieure des mines de Nantes",
  "École supérieure angevine d'informatique et de productique",
  "École supérieure d'électronique de l'Ouest",
  "École supérieure d'agriculture d'Angers",
  "École supérieure du bois",
  "Institut supérieur des matériaux du Mans",
  "École polytechnique de l'université de Nice",
  "Institut des sciences de l'ingénieur de Toulon et du Var de l'université de Toulon",
  "École nationale supérieure d'ingénieurs de Bourges",
  "École polytechnique de l'université d'Orléans",
  "École polytechnique de l'université de Tours",
  "École nationale supérieure de mécanique et d'aérotechnique de Poitiers",
  "École nationale supérieure d'ingénieurs de Poitiers de l'université de Poitiers",
  "École d'ingénieurs en génie des systèmes industriels",
  "Université de technologie de Troyes",
  "École nationale d'ingénieurs de Brest",
  "École nationale supérieure de chimie de Rennes",
  "Institut national des sciences appliquées de Rennes",
  "École supérieure d'ingénieurs en agroalimentaire de Bretagne atlantique de l’université de Brest",
  "École nationale supérieure de sciences appliquées et de technologie de Lannion de l'université Rennes-I",
  "École supérieure d’ingénieurs de Rennes de l’université Rennes-I",
  "Institut supérieur des sciences agronomiques, agroalimentaires, horticoles et du paysage (Agrocampus Ouest)",
  "École nationale supérieure de techniques avancées Bretagne",
  "Ecam Rennes, Louis de Broglie",
  "Institut supérieur de l'électronique et du numérique de Brest",
  "École des métiers de l'environnement",
  "École supérieure d'ingénieurs Réunion océan Indien de l'université de La Réunion",
  "Institut national des sciences appliquées de Rouen",
  "Esitpa, école d’ingénieurs en agriculture",
  "École supérieure d'ingénieurs en génie électrique",
  "Institut national des sciences appliquées de Strasbourg",
  "École nationale supérieure de chimie de Mulhouse de l’université de Mulhouse",
  "École nationale supérieure d'ingénieurs Sud-Alsace de l’université de Mulhouse",
  "École et observatoire des sciences de la Terre de l'université de Strasbourg",
  "École européenne de chimie, polymères et matériaux de Strasbourg de l'université de Strasbourg",
  "École supérieure de biotechnologie de Strasbourg de l'université de Strasbourg",
  "École nationale du génie de l'eau et de l'environnement de Strasbourg",
  "École nationale d'ingénieurs de Tarbes",
  "École nationale supérieure agronomique de Toulouse de l'Institut national polytechnique de Toulouse",
  "École nationale supérieure des ingénieurs en arts chimiques et technologiques de l'Institut national polytechnique de Toulouse",
  "École nationale supérieure d'électrotechnique, d'électronique, d'informatique, d'hydraulique et des télécommunications de l'Institut national polytechnique de Toulouse",
  "Institut national des sciences appliquées de Toulouse de l'Institut national polytechnique de Toulouse",
  "Institut supérieur de l’aéronautique et de l’espace",
  "École nationale de l'aviation civile",
  "École nationale de la météorologie",
  "École nationale supérieure des mines d'Albi-Carmaux",
  "École d’ingénieurs de Purpan",
  "École nationale supérieure d'arts et métiers",
  "École nationale supérieure de chimie de Paris",
  "École polytechnique universitaire Pierre et Marie Curie de l'université Paris-VI",
  "Institut des sciences et industries du vivant et de l'environnement (AgroParisTech)",
  "École nationale supérieure des mines de Paris",
  "École des ingénieurs de la ville de Paris",
  "École supérieure de physique et de chimie industrielles de la ville de Paris",
  "École centrale d'électronique",
  "École supérieure d'informatique, électronique, automatique",
  "Institut supérieur d'électronique de Paris",
  "Institut catholique d'arts et métiers",
  "Institut supérieur de mécanique de Paris",
  "École nationale des sciences géographiques",
  "École supérieure d'ingénieurs des travaux de la construction de Cachan",
  "École spéciale de mécanique et d'électricité",
  "École pour l'informatique et les techniques avancées",
  "Institut polytechnique des sciences avancées",
  "École spéciale des travaux publics, du bâtiment et de l'industrie",
  "École nationale supérieure de l'électronique et de ses applications",
  "École nationale supérieure d'informatique pour l'industrie et l'entreprise",
  "Institut des sciences et techniques des Yvelines de l'université de Versailles-Saint Quentin en Yvelines",
  "École polytechnique de l'université Paris-XI",
  "École polytechnique",
  "École de biologie industrielle",
  "École internationale des sciences du traitement de l'information",
  "École supérieure des techniques aéronautiques et de construction automobile",
  "Institut d'optique théorique et appliquée",
  "École supérieure d'ingénieurs Léonard de Vinci",
  "ISTOM",
  "École supérieure de fonderie et de forge en convention avec l'Institut supérieur de mécanique de Paris",
  "École nationale de la statistique et de l’administration économique du Groupe des Écoles nationales d’économie et statistique",
  "École nationale supérieure de techniques avancées",
  "Audencia",
  "Brest Business School",
  "European Business School Paris",
  "EDC Paris",
  "École des hautes études commerciales du nord (EDHEC)",
  "École de management de Normandie",
  "École de management Strasbourg",
  "École de management de Lyon",
  "École supérieure de commerce de Dijon",
  "École supérieure de commerce de La Rochelle",
  "École supérieure de commerce de Pau",
  "École supérieure de commerce de Rennes",
  "École supérieure de commerce de Troyes",
  "École supérieure du commerce extérieur",
  "École supérieure de commerce de Paris - Europe (ESCP Europe)",
  "École supérieure pour le développement économique et social",
  "Paris School of Business",
  "École supérieure des sciences commerciales d'Angers",
  "École supérieure des sciences économiques et commerciales (ESSEC)",
  "Grenoble École de management",
  "École supérieure de commerce de Clermont",
  "École des hautes études commerciales de Paris (HEC Paris)",
  "Institut international du commerce et du développement",
  "ICN Business School",
  "Institut de recherche et d’action commerciale (IDRAC)",
  "Institut d’économie scientifique et de gestion (IESEG)",
  "Institut européen d'administration des affaires (INSEAD)",
  "Institut des hautes études économiques et commerciales (INSEEC)",
  "Institut de préparation à l’administration et à la gestion",
  "Institut supérieur du commerce de Paris",
  "Institut supérieur de gestion",
  "Institut supérieur des sciences, techniques et économie commerciales",
  "Kedge Business School",
  "Montpellier Business School",
  "Neoma Business School",
  "Novancia Business School Paris",
  "Skema Business School",
  "Télécom École de management",
  "Toulouse Business School"
]

french_schools.each do |school_name|
  School.find_or_create_by(name: school_name)
end
