# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7767ab66b439ee59e5d44d9de5f6916f4ffbf9919c74e9df1e3664265a8e7edc2f94b04379d773071f3658d3fdcf458585eda777c10855b80423ed56563b6655

test:
  secret_key_base: 6acaa26e5e0f0e7df1bdf041e2cbb1c7ef2c292c2272800770dfcf1c3e6b352450f9b141bc8f370fd6eee86e64949317e4c0588d0463a0ec71fe5fd7abab3558

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>

staging:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>